name: Server Deploy

on:
  push:
    branches: ['main', 'dockerise']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: echo $SSH_AUTH_SOCK
      - run: docker context create remote --docker "host=ssh://opc@168.138.8.111"
      - run: docker-compose --context remote up --build -d --force-recreate  
    